// <auto-generated />
using System;
using System.Collections.Generic;
using BwMelder.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BwMelder.Core.Migrations
{
    [DbContext(typeof(BwMelderDbContext))]
    [Migration("20250129163510_InitializeDatabase")]
    partial class InitializeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BwMelder.Core.Model.AccessKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("AccessKeys");
                });

            modelBuilder.Entity("BwMelder.Core.Model.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("BwMelder.Core.Model.ClubCoach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Contact", "BwMelder.Core.Model.ClubCoach.Contact#Contact", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "BwMelder.Core.Model.ClubCoach.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("First")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Last")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .IsUnique();

                    b.ToTable("ClubCoaches");
                });

            modelBuilder.Entity("BwMelder.Core.Model.Crew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("RaceId");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("BwMelder.Core.Model.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPublicTransportTicket")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShirtSize")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "BwMelder.Core.Model.Participant.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Zip")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Diet", "BwMelder.Core.Model.Participant.Diet#Diet", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Choice")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Restrictions")
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "BwMelder.Core.Model.Participant.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("First")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Last")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("Participants", (string)null);

                    b.HasDiscriminator().HasValue("Participant");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BwMelder.Core.Model.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Coxed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CrewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowerCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("BwMelder.Core.Model.Athlete", b =>
                {
                    b.HasBaseType("BwMelder.Core.Model.Participant");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty<Dictionary<string, object>>("LegalGuardian", "BwMelder.Core.Model.Athlete.LegalGuardian#LegalGuardian", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Contact", "BwMelder.Core.Model.Athlete.LegalGuardian#LegalGuardian.Contact#Contact", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("EmailAddress")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Phone")
                                        .IsRequired()
                                        .HasColumnType("TEXT");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Name", "BwMelder.Core.Model.Athlete.LegalGuardian#LegalGuardian.Name#Name", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("First")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Last")
                                        .IsRequired()
                                        .HasColumnType("TEXT");
                                });
                        });

                    b.HasIndex("CrewId");

                    b.HasDiscriminator().HasValue("Athlete");
                });

            modelBuilder.Entity("BwMelder.Core.Model.TeamCoach", b =>
                {
                    b.HasBaseType("BwMelder.Core.Model.Participant");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DriversLicense")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty<Dictionary<string, object>>("Contact", "BwMelder.Core.Model.TeamCoach.Contact#Contact", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasIndex("ClubId");

                    b.HasDiscriminator().HasValue("TeamCoach");
                });

            modelBuilder.Entity("BwMelder.Core.Model.AccessKey", b =>
                {
                    b.HasOne("BwMelder.Core.Model.Club", null)
                        .WithMany("AccessKeys")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BwMelder.Core.Model.ClubCoach", b =>
                {
                    b.HasOne("BwMelder.Core.Model.Club", null)
                        .WithOne("ClubCoach")
                        .HasForeignKey("BwMelder.Core.Model.ClubCoach", "ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BwMelder.Core.Model.Crew", b =>
                {
                    b.HasOne("BwMelder.Core.Model.Club", "Club")
                        .WithMany("Crews")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BwMelder.Core.Model.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("BwMelder.Core.Model.Athlete", b =>
                {
                    b.HasOne("BwMelder.Core.Model.Crew", null)
                        .WithMany("Athletes")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BwMelder.Core.Model.TeamCoach", b =>
                {
                    b.HasOne("BwMelder.Core.Model.Club", null)
                        .WithMany("TeamCoaches")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BwMelder.Core.Model.Club", b =>
                {
                    b.Navigation("AccessKeys");

                    b.Navigation("ClubCoach");

                    b.Navigation("Crews");

                    b.Navigation("TeamCoaches");
                });

            modelBuilder.Entity("BwMelder.Core.Model.Crew", b =>
                {
                    b.Navigation("Athletes");
                });
#pragma warning restore 612, 618
        }
    }
}
