// <auto-generated />
using System;
using BwMelder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BwMelder.Migrations
{
    [DbContext(typeof(BwMelderDbContext))]
    partial class BwMelderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BwMelder.Model.AccessKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("AccessKeys");
                });

            modelBuilder.Entity("BwMelder.Model.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("BwMelder.Model.ClubCoach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .IsUnique();

                    b.ToTable("ClubCoaches");
                });

            modelBuilder.Entity("BwMelder.Model.Crew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("BwMelder.Model.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPublicTransportTicket")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShirtSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Participants", (string)null);

                    b.HasDiscriminator().HasValue("Participant");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BwMelder.Model.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Coxed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowerCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("BwMelder.Model.Athlete", b =>
                {
                    b.HasBaseType("BwMelder.Model.Participant");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CrewId");

                    b.HasDiscriminator().HasValue("Athlete");
                });

            modelBuilder.Entity("BwMelder.Model.TeamCoach", b =>
                {
                    b.HasBaseType("BwMelder.Model.Participant");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DriversLicense")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ClubId");

                    b.HasDiscriminator().HasValue("TeamCoach");
                });

            modelBuilder.Entity("BwMelder.Model.AccessKey", b =>
                {
                    b.HasOne("BwMelder.Model.Club", null)
                        .WithMany("AccessKeys")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BwMelder.Model.ClubCoach", b =>
                {
                    b.HasOne("BwMelder.Model.Club", null)
                        .WithOne("ClubCoach")
                        .HasForeignKey("BwMelder.Model.ClubCoach", "ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BwMelder.Model.Contact", "Contact", b1 =>
                        {
                            b1.Property<int>("ClubCoachId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ClubCoachId");

                            b1.ToTable("ClubCoaches");

                            b1.WithOwner()
                                .HasForeignKey("ClubCoachId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("BwMelder.Model.Crew", b =>
                {
                    b.HasOne("BwMelder.Model.Club", null)
                        .WithMany("Crews")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BwMelder.Model.Participant", b =>
                {
                    b.OwnsOne("BwMelder.Model.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Zip")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ParticipantId");

                            b1.ToTable("Participants");

                            b1.WithOwner()
                                .HasForeignKey("ParticipantId");
                        });

                    b.OwnsOne("BwMelder.Model.Diet", "Diet", b1 =>
                        {
                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Choice")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Restrictions")
                                .HasColumnType("TEXT");

                            b1.HasKey("ParticipantId");

                            b1.ToTable("Participants");

                            b1.WithOwner()
                                .HasForeignKey("ParticipantId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Diet")
                        .IsRequired();
                });

            modelBuilder.Entity("BwMelder.Model.Athlete", b =>
                {
                    b.HasOne("BwMelder.Model.Crew", null)
                        .WithMany("Athletes")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BwMelder.Model.LegalGuardian", "LegalGuardian", b1 =>
                        {
                            b1.Property<Guid>("AthleteId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("AthleteId");

                            b1.ToTable("Participants");

                            b1.WithOwner()
                                .HasForeignKey("AthleteId");

                            b1.OwnsOne("BwMelder.Model.Contact", "Contact", b2 =>
                                {
                                    b2.Property<Guid>("LegalGuardianAthleteId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("EmailAddress")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Phone")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("LegalGuardianAthleteId");

                                    b2.ToTable("Participants");

                                    b2.WithOwner()
                                        .HasForeignKey("LegalGuardianAthleteId");
                                });

                            b1.Navigation("Contact")
                                .IsRequired();
                        });

                    b.Navigation("LegalGuardian")
                        .IsRequired();
                });

            modelBuilder.Entity("BwMelder.Model.TeamCoach", b =>
                {
                    b.HasOne("BwMelder.Model.Club", null)
                        .WithMany("TeamCoaches")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BwMelder.Model.Contact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("TeamCoachId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("TeamCoachId");

                            b1.ToTable("Participants");

                            b1.WithOwner()
                                .HasForeignKey("TeamCoachId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("BwMelder.Model.Club", b =>
                {
                    b.Navigation("AccessKeys");

                    b.Navigation("ClubCoach");

                    b.Navigation("Crews");

                    b.Navigation("TeamCoaches");
                });

            modelBuilder.Entity("BwMelder.Model.Crew", b =>
                {
                    b.Navigation("Athletes");
                });
#pragma warning restore 612, 618
        }
    }
}
