<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2917077f-6396-435b-98d5-5de4d677ada0</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.DataAnnotations.Validation" Version="3.2.0-rc1.20223.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="2.1.175" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BwMelder.Data\BwMelder.Data.csproj" />
    <ProjectReference Include="..\BwMelder.Services\BwMelder.Services.csproj" />
    <ProjectReference Include="..\BwMelder.Shared\BwMelder.Shared.csproj" />
  </ItemGroup>

</Project>
